//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLNOTLAR
    {
        public int NotId { get; set; }
        [Required(ErrorMessage ="Ders Alanı Boş Geçilemez.")]
        public Nullable<int> DersId { get; set; }
        [Required(ErrorMessage ="Ogrenci Alanı Boş Geçilemez.")]
        public Nullable<int> OgrId { get; set; }
        [Required(ErrorMessage ="Sınav 1 Alanı Boş Geçilemez.")]
        public Nullable<int> Sinav1 { get; set; }
        [Required(ErrorMessage ="Sinav 2 Alanı Boş Geçilemez.")]
        public Nullable<int> Sinav2 { get; set; }
        [Required(ErrorMessage ="Sınav 3 Alanı Boş Geçilemez.")]
        public Nullable<int> Sinav3 { get; set; }
        [Required(ErrorMessage ="Proje Alanı Boş Geçilemez.")]
        public Nullable<int> Proje { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TBLDERSLER TBLDERSLER { get; set; }
        public virtual TBLOGRENCİ TBLOGRENCİ { get; set; }
    }
}
